# Judge0 Configuration
PORT=2358
RAILS_MAX_THREADS=10
BIND_ADDRESS=0.0.0.0

POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0
POSTGRES_DB=judge0

REDIS_HOST=redis
REDIS_PORT=6379

MAX_MEMORY_LIMIT=1024000
MAX_CPU_TIME_LIMIT=15.0
MAX_WALL_TIME_LIMIT=30.0
MAX_STACK_LIMIT=128000
MAX_MAX_PROCESSES_AND_OR_THREADS=120
MAX_MAX_FILE_SIZE=10240

ENABLE_ISOLATE_CGROUP=false
USE_CGROUP=false
BOX_USE_CGROUP=false
ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=true
ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=true
