"""add teacher invitations

Revision ID: 12174c995d8c
Revises: 50379f94c158
Create Date: 2026-08-14 03:01:01.673667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12174c995d8c'
down_revision: Union[str, Sequence[str], None] = '50379f94c158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_invitations',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_invitations_email'), 'teacher_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_teacher_invitations_status'), 'teacher_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_teacher_invitations_token_hash'), 'teacher_invitations', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_invitations_token_hash'), table_name='teacher_invitations')
    op.drop_index(op.f('ix_teacher_invitations_status'), table_name='teacher_invitations')
    op.drop_index(op.f('ix_teacher_invitations_email'), table_name='teacher_invitations')
    op.drop_table('teacher_invitations')
    # ### end Alembic commands ###
